Obey clippy::filter_next
It was not initially clear to me why, after changing
`.filter(...).next()` to `.find(...)`, the borrow checker as of Rust
1.41.1 required me to inline `all.lines()` at this point :

    error[E0596]: cannot borrow `lines` as mutable, as it is not declared as mutable
      --> tyrga-bin/../build.rs:53:33
       |
    52 |                     let lines = all.lines();
       |                         ----- help: consider changing this to be mutable: `mut lines`
    53 |                     let wrote = lines
       |                                 ^^^^^ cannot borrow as mutable

    error: aborting due to previous error

    For more information about this error, try `rustc --explain E0596`.

but it [appears][0] that the new error is [expected][1], and that if I
had been using `.find()` previously instead of `.filter(...).next()`, I
would have seen a non-fatal "compat" lint under previous compiler
versions, leading me in the same direction.

[0]: https://github.com/rust-lang/rust/issues/68729
[1]: https://github.com/rust-lang/rust/pull/65785